services:
  - type: web
    name: task-manager
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: DB_CONNECTION
        fromDatabase:
          name: task-manager-db
          property: connectionString
      # Add other environment variables here as needed
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    port: 80
